openvinotoolkit/docker_ci

- templates/ubuntu18/common/base.dockerfile.j2
- templates/ubuntu18/dist/data_dev.dockerfile.j2
- templates/ubuntu18/dist/dev.dockerfile.j2
- templates/ubuntu18/dist/internal_dev.dockerfile.j2
- templates/ubuntu18/dist/proprietary.dockerfile.j2
- templates/ubuntu18/install/install.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- templates/ubuntu20/dist/data_dev.dockerfile.j2
- templates/ubuntu20/install/install.dockerfile.j2
- tests/functional/demos/test_demos_linux.py
- tests/functional/demos/test_demos_linux_runtime.py
- tests/functional/samples/test_samples_linux.py
- tests/functional/samples/test_samples_linux_runtime.py
Remove build-essential (GPL) and install directly gcc and libc.
> build: update sample build deps

- dockerfiles/centos7/openvino_cgvh_runtime_2021.dockerfile
- dockerfiles/centos8/openvino_c_runtime_2021.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_data_dev_2021.2.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_data_runtime_2021.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_dev_2021.2.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_proprietary_2021.2.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_runtime_2021.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_data_runtime_2021.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_runtime_2021.dockerfile
- get-started.md
- templates/centos7/common/base.dockerfile.j2
- templates/centos7/hw/vpu.dockerfile.j2
- templates/centos8/common/base.dockerfile.j2
- templates/ubuntu18/common/base.dockerfile.j2
- templates/ubuntu18/hw/vpu.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- templates/ubuntu20/hw/vpu.dockerfile.j2
- tests/functional/demos/test_demos_linux.py
- tests/functional/demos/test_demos_windows.py
- utils/arg_parser.py
> fix: download source for 3d party packages

- .github/workflows/manual_publish.yml
- dockerfiles/README.md
- dockerfiles/centos7/openvino_cgvh_runtime_2021.dockerfile
- dockerfiles/centos8/openvino_c_runtime_2021.dockerfile
- dockerfiles/rhel8/openvino_c_runtime_2021.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_data_dev_2021.2.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_data_runtime_2021.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_dev_2021.2.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_proprietary_2021.2.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_runtime_2021.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_data_runtime_2021.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_runtime_2021.dockerfile
- get-started.md
- templates/centos7/common/base.dockerfile.j2
- templates/centos8/common/base.dockerfile.j2
- templates/ubuntu18/common/base.dockerfile.j2
- templates/ubuntu18/dist/data_dev.dockerfile.j2
- templates/ubuntu18/dist/dev.dockerfile.j2
- templates/ubuntu18/dist/proprietary.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- templates/ubuntu20/dist/data_dev.dockerfile.j2
- templates/ubuntu20/dist/dev.dockerfile.j2
- tests/functional/test_pypi_deps.py
- tests/resources/pypi_deps/get_gpl_packages.py
- utils/arg_parser.py
build: add download LGPL PyPi pkgs, remove venv for ubuntu20 …
test: separate conflicts and gpl pypi tests
> build: update source for pypi 3d pkgs

- tests/conftest.py
- tests/functional/test_pypi_changes.py
- tests/resources/pypi_deps/centos7_runtime_2021.3.json
- tests/resources/pypi_deps/get_gpl_packages.py
- tests/resources/pypi_deps/pypi_deps_manager.py
- tests/resources/pypi_deps/ubuntu18_data_dev_2021.3.json
- tests/resources/pypi_deps/ubuntu18_data_runtime_2021.3.json
- tests/resources/pypi_deps/ubuntu18_dev_2021.3.json
- tests/resources/pypi_deps/ubuntu18_runtime_2021.3.json
- tests/resources/pypi_deps/ubuntu20_data_dev_2021.3.json
- tests/resources/pypi_deps/ubuntu20_data_runtime_2021.3.json
- tests/resources/pypi_deps/ubuntu20_dev_2021.3.json
- tests/resources/pypi_deps/ubuntu20_runtime_2021.3.json
added test to save PyPi deps for current image: -m save_pypi_deps -k save_pypi_deps
> test: add check PyPi changes

- tests/conftest.py
- tests/functional/demos/test_demos_linux.py
- tests/functional/samples/test_samples_linux.py
- tests/functional/samples/test_samples_linux_runtime.py
- tests/functional/test_base_cpu.py
- tests/functional/test_dl_streamer.py
- tests/resources/base_cpu/demo.sh
`apt install wget` remains in [dl_streamer audio_detect sample test](https://github.com/openvinotoolkit/docker_ci/blob/52d16b45052d92da7c0e5d20bf2c16642098f645/tests/functional/test_dl_streamer.py#L80)
> Refactor apt usage

- tests/conftest.py
- tests/functional/demos/test_demos_linux.py
- tests/functional/demos/test_demos_linux_runtime.py
- tests/functional/demos/test_demos_windows.py
- tests/functional/test_dl_streamer.py
- tests/functional/test_linux_changes.py
- tests/functional/test_linux_deps.py
> Fix OMZ demos path

- templates/ubuntu20/install/install.dockerfile.j2
> build: fix missing backslash in ubuntu20 install template

- dockerfiles/ubuntu18/build_custom/Dockerfile
See https://github.com/opencv/opencv/commit/3dd55d284d5d28fa08f6c7f081f53e868c32fdd1
> custom: add libva-dev to build opencv

- dockerfiles/ubuntu20/openvino_cgvh_data_runtime_2021.3.dockerfile
- templates/ubuntu18/common/base.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- tests/resources/pypi_deps/pip_known_issues.txt
> build: add intel-media-va-driver-non-free for Ubuntu 20 data_runtime image

- dockerfiles/ubuntu18/openvino_cgvh_data_dev_2021.3.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_data_runtime_2021.3.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_dev_2021.3.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_proprietary_2021.3.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_runtime_2021.3.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_data_dev_2021.3.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_data_runtime_2021.3.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_dev_2021.3.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_runtime_2021.3.dockerfile
- templates/centos7/dist/runtime.dockerfile.j2
- templates/ubuntu18/common/base.dockerfile.j2
- templates/ubuntu18/dist/data_dev.dockerfile.j2
- templates/ubuntu18/dist/data_runtime.dockerfile.j2
- templates/ubuntu18/dist/dev.dockerfile.j2
- templates/ubuntu18/dist/internal_dev.dockerfile.j2
- templates/ubuntu18/dist/proprietary.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- templates/ubuntu20/dist/data_dev.dockerfile.j2
- templates/ubuntu20/dist/data_runtime.dockerfile.j2
- templates/ubuntu20/dist/dev.dockerfile.j2
- templates/winserver2019/dist/data_dev.dockerfile.j2
- templates/winserver2019/dist/dev.dockerfile.j2
- templates/winserver2019/dist/proprietary.dockerfile.j2
- tests/resources/pypi_deps/ubuntu18_runtime_2021.3.json
- tests/resources/pypi_deps/ubuntu20_runtime_2021.3.json
* set env variable DEBIAN_FRONTEND=noninteractive
* remove opencv-python pip package from images after 2021.3
* add python3-gi-cairo package to data_dev and data_runtime Ubuntu 20 images
> Fixes for dockerfiles

- templates/rhel8/layers/benchmark.dockerfile.j2
Internal ticket 52671
Build it on internal CI: add `--layers benchmark` to LAYER field
> feat: benchmark layer

- tests/conftest.py
- tests/resources/pypi_deps/pypi_deps_manager.py
- tests/resources/pypi_deps/ubuntu18_dev_2021.4.json
I will add save_dep to our regular tests to get deps for each package
Internal PR: 50
> feat: track PyPI POT dependencies

- docker_openvino.py
- templates/ubuntu18/dist/dev_no_samples.dockerfile.j2
- templates/ubuntu18/hw/gpu.dockerfile.j2
- templates/ubuntu18/install/copy.dockerfile.j2
- templates/ubuntu18/install/install.dockerfile.j2
- utils/arg_parser.py
- utils/render.py
Add a new dev_no_samples distribution for Workbench needs. It doesn't have samples, demos, pypi dependencies for frameworks and has 20.35.17767 GPU driver by default.
> feat: dev_no_samples dist

- docker_openvino.py
Build on Azure passed: https://github.com/ilya-naumov/docker_ci/runs/2500801334?check_suite_focus=true
> build: fix ConnectionResetError if openshift parameter is False

- templates/centos7/common/base.dockerfile.j2
- templates/centos8/common/base.dockerfile.j2
- templates/rhel8/common/base.dockerfile.j2
- templates/ubuntu18/common/base.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- templates/winserver2019/common/base.dockerfile.j2
> build: create file for distribution channel id

- templates/centos7/layers/wheel.dockerfile.j2
- templates/rhel8/layers/wheel.dockerfile.j2
- templates/ubuntu18/layers/wheel.dockerfile.j2
- templates/ubuntu20/layers/wheel.dockerfile.j2
- tests/resources/pypi_deps/centos7_runtime_2021.4.json
- tests/resources/pypi_deps/pypi_deps_manager.py
- tests/resources/pypi_deps/rhel8_runtime_2021.4.json
- tests/resources/pypi_deps/ubuntu18_data_dev_2021.4.json
- tests/resources/pypi_deps/ubuntu18_data_runtime_2021.4.json
- tests/resources/pypi_deps/ubuntu18_runtime_2021.4.json
- tests/resources/pypi_deps/ubuntu20_data_dev_2021.4.json
- tests/resources/pypi_deps/ubuntu20_data_runtime_2021.4.json
- tests/resources/pypi_deps/ubuntu20_dev_2021.4.json
- tests/resources/pypi_deps/ubuntu20_runtime_2021.4.json
Also update data for test_pypi_changes
> Add custom wheel installation layer for Linux images

- dockerfiles/ubuntu18/build_custom/Dockerfile
it helps to clean that images by lable
> build: add Intel label to custom build

- get-started.md
- utils/arg_parser.py
- utils/tests/test_arg_parser.py
> feature: add TGL and postfix tags

- dockerfiles/ubuntu18/openvino_cgvh_data_dev_2021.4.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_data_runtime_2021.4.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_dev_2021.4.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_proprietary_2021.4.dockerfile
- dockerfiles/ubuntu18/openvino_cgvh_runtime_2021.4.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_data_dev_2021.4.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_data_runtime_2021.4.dockerfile
- dockerfiles/ubuntu20/openvino_cgvh_runtime_2021.4.dockerfile
- templates/ubuntu18/common/base.dockerfile.j2
- templates/ubuntu18/hw/vpu.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
> build: remove dpkg-dev from Ubuntu

- dockerfiles/rhel8/autobuild/openvino_cg_runtime_2021.4.dockerfile
merge after AWS upload and check on Rhel build service
> build: add 2021.4 rhel autobuild Dockerfile

- install_guide_vpu_hddl.md
- utils/loader.py
Please merge after uploading to AWS. @ilya-naumov
> build: add 2021.4 pkg links

- .github/workflows/hadolint_check.yml
https://github.com/ilya-naumov/docker_ci/pull/16/checks?check_run_id=2960803091
> ci: add workflow to hadolint check changed dockerfiles in PR

- tests/functional/demos/test_demos_linux.py
- tests/functional/demos/test_demos_windows.py
- tests/resources/linux_deps/ubuntu20_data_dev_2021.4.txt
- tests/resources/linux_deps/ubuntu20_data_runtime_2021.4.txt
- tests/resources/linux_deps/ubuntu20_dev_2021.4.txt
- tests/resources/linux_deps/ubuntu20_runtime_2021.4.txt
also update apt packages lists for Ubuntu 20 images
> test: add test for speech recognition demo

- dockerfiles/windows20h2/third-party-programs-docker-runtime.txt
- tests/functional/test_package_licenses.py
cherry-pick from release 2021/4
> test: check 3d party file exist (#163)

- dockerfiles/ubuntu18/third-party-programs-docker-data-dev.txt
- dockerfiles/ubuntu18/third-party-programs-docker-data-runtime.txt
- dockerfiles/ubuntu20/third-party-programs-docker-data-dev.txt
- dockerfiles/ubuntu20/third-party-programs-docker-data-runtime.txt
- templates/ubuntu18/dist/data_dev.dockerfile.j2
- templates/ubuntu18/dist/data_runtime.dockerfile.j2
- templates/ubuntu18/dist/dev.dockerfile.j2
- templates/ubuntu18/dist/dev_no_samples.dockerfile.j2
- templates/ubuntu18/dist/internal_dev.dockerfile.j2
- templates/ubuntu18/dist/proprietary.dockerfile.j2
- templates/ubuntu20/dist/data_dev.dockerfile.j2
- templates/ubuntu20/dist/data_runtime.dockerfile.j2
- templates/ubuntu20/dist/dev.dockerfile.j2
- tests/functional/samples/test_samples_linux.py
add missing commits from release to master
> feat: add 3dparty data files

- .github/workflows/update_dockerfiles.yml
- docker_openvino.py
- templates/rhel8/common/base.dockerfile.j2
- templates/rhel8/dist/dev.dockerfile.j2
- templates/rhel8/install/copy.dockerfile.j2
- templates/rhel8/source/local.dockerfile.j2
- templates/rhel8/source/url.dockerfile.j2
- tests/functional/demos/test_demos_linux.py
- tests/functional/samples/test_samples_linux.py
- utils/arg_parser.py
- utils/render.py
- utils/tests/test_arg_parser.py
* Generate dockerfiles for Red Hat portal Build System (`--rhel_platform=[docker, openshift, autobuild]`
* Enable tests for `run_sample_*.sh` on RHEL, add test for `run_sample_benchmark_app.sh`
* Move sample scripts tests to samples file
> feat: improvements for RHEL images

- templates/rhel8/dist/dev.dockerfile.j2
- templates/rhel8/dist/runtime.dockerfile.j2
- templates/ubuntu18/dist/dev.dockerfile.j2
- templates/ubuntu18/dist/dev_no_samples.dockerfile.j2
- templates/ubuntu18/dist/internal_dev.dockerfile.j2
- templates/ubuntu18/dist/proprietary.dockerfile.j2
- templates/ubuntu18/dist/runtime.dockerfile.j2
- templates/ubuntu20/dist/dev.dockerfile.j2
- templates/ubuntu20/dist/dev_no_samples.dockerfile.j2
- templates/ubuntu20/dist/runtime.dockerfile.j2
- templates/windows20h2/dist/dev.dockerfile.j2
- templates/windows20h2/dist/proprietary.dockerfile.j2
- templates/windows20h2/dist/runtime.dockerfile.j2
- templates/winserver2019/dist/dev.dockerfile.j2
- templates/winserver2019/dist/proprietary.dockerfile.j2
- templates/winserver2019/dist/runtime.dockerfile.j2
> DockerTemplates: Added supporting dev-wheels

- .github/workflows/manual_publish.yml
also add build and publish support for images based on Windows 20H2
> ci: use custom Windows runner for manual publish job

- dockerfiles/ubuntu18/build_custom/Dockerfile
- dockerfiles/ubuntu18/build_custom/README.md
- dockerfiles/ubuntu20/build_custom/Dockerfile
- dockerfiles/ubuntu20/build_custom/README.md
- tests/conftest.py
> build: simplify custom dockerfile building without OpenVINO sources

- templates/windows20h2/cmake/cmake314.dockerfile.j2
- templates/windows20h2/cmake/cmake34.dockerfile.j2
- templates/windows20h2/msbuild/msbuild2019.dockerfile.j2
- templates/windows20h2/msbuild/msbuild2019_online.dockerfile.j2
- templates/windows20h2/python/pre_python38.dockerfile.j2
- templates/windows20h2/redist/vs.dockerfile.j2
- templates/winserver2019/cmake/cmake314.dockerfile.j2
- templates/winserver2019/cmake/cmake34.dockerfile.j2
- templates/winserver2019/msbuild/msbuild2019.dockerfile.j2
- templates/winserver2019/msbuild/msbuild2019_online.dockerfile.j2
- templates/winserver2019/python/pre_python38.dockerfile.j2
- templates/winserver2019/redist/vs.dockerfile.j2
- tests/conftest.py
- tests/linters/test_dockerfile.py
- tests/linters/test_linter_image.py
- tests/security/test_host.py
- tests/security/test_image.py
- utils/arg_parser.py
- utils/tests/check_loader_links.py
- utils/tests/test_utilities.py
Fix offline execution for windows docker image
Resolve CI style tests
> Windows building improvements

- dockerfiles/rhel8/openvino_cg_dev_2023.0.0.dockerfile
- dockerfiles/rhel8/openvino_cg_runtime_2023.0.0.dockerfile
- dockerfiles/ubuntu20/openvino_cg_runtime_2023.0.0.dockerfile
- dockerfiles/ubuntu22/openvino_cg_runtime_2023.0.0.dockerfile
- templates/rhel8/common/base.dockerfile.j2
- templates/rhel8/dist/runtime.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- templates/ubuntu20/dist/runtime.dockerfile.j2
- templates/ubuntu22/common/base.dockerfile.j2
- templates/ubuntu22/dist/runtime.dockerfile.j2
- tests/functional/demos/test_demos_linux.py
- tests/functional/samples/test_samples_linux.py
- tests/functional/samples/test_samples_linux_runtime.py
- tests/functional/test_base_cpu.py
- tests/functional/test_python_bindings_linux.py
- tests/functional/test_setupvars_changes.py
- tests/functional/test_tools_linux.py
- tests/security/test_image.py
- tests/thirdparty/test_linux_changes.py
- tests/thirdparty/test_linux_deps.py
- tests/thirdparty/test_package_licenses.py
- tests/thirdparty/test_pypi_changes.py
Drop from runtime images all building tools and duplicated pip openvino package
UBI base image changed to 8.8 release
Added  tests for ubuntu22
> Shrink runtime images

- templates/rhel8/common/base.dockerfile.j2
- templates/ubuntu20/common/base.dockerfile.j2
- templates/ubuntu22/common/base.dockerfile.j2
> [dockerfiles] Disabled dnn and gapi in opencv to fix build issue

- dockerfiles/rhel8/openvino_cg_dev_2023.0.0.dockerfile
- dockerfiles/ubuntu20/openvino_cg_dev_2023.0.0.dockerfile
- dockerfiles/ubuntu22/openvino_cg_dev_2023.0.0.dockerfile
- templates/rhel8/dist/dev.dockerfile.j2
- templates/ubuntu20/dist/dev.dockerfile.j2
- templates/ubuntu22/dist/dev.dockerfile.j2
[New usage](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/common/python/model_zoo/model_api#readme:~:text=python%20%2Dc%20%22from%20model_zoo%20import%20model_api%22)
> [Dockerfiles] Changed model_api usage
